### ISSUE TITLE
user新規登録

### ISSUE THREAD

**Issue by itouayumu** [morijyobi/python_flask_web_final_exercise_2023-itouayumu#6]
##新規登録
目的
- 入力値が重複していなければデータベースにアカウントを追加する

- [x] 各テキストボックス配置
- [x] 更新系sql追記
<img width="499" alt="image" src="https://github.com/morijyobi/python_flask_web_final_exercise_2023-itouayumu/assets/113155843/94b57cbd-dd21-4d16-b152-69fffeb10291">

**Comment by itouayumu** [comment]
作成完了
css設定完了
<img width="960" alt="image" src="https://github.com/morijyobi/python_flask_web_final_exercise_2023-itouayumu/assets/113155843/1e6ec74d-e381-48ba-a08f-de4711b3e9d8">

**Comment by itouayumu** [comment]
- [ ] PRGパターン実装

**Comment by itouayumu** [comment]
PRGパターン実装完了

**Comment by hosokawa3217** [comment]
授業で教わったことの実装ですね。Great！！

**Comment by hosokawa3217** [comment]
「作業中」ラベルをはがすか、「完了」ラベルに付け替えましょう。
