### ISSUE TITLE
pass変更申請ページ

### ISSUE THREAD

**Issue by itouayumu** [morijyobi/python_flask_web_final_exercise_2023-itouayumu#7]
##パスワード変更ページ
目的
-メールアドレスを入力してもらいデータベースに一致するものがあればパスワード変更案内メールを送信する

- [ ] メール入力用のテキストボックス配置
- [ ] メール送信処理
- [ ] url

**Comment by hosokawa3217** [comment]
確認しました！

**Comment by itouayumu** [comment]
<img width="393" alt="image" src="https://github.com/morijyobi/python_flask_web_final_exercise_2023-itouayumu/assets/113155843/ca4f08f7-fbfb-4e6a-a0f6-9512927612e1">

**Comment by hosokawa3217** [comment]
確認しました！

**Comment by itouayumu** [comment]
<img width="665" alt="image" src="https://github.com/morijyobi/python_flask_web_final_exercise_2023-itouayumu/assets/113155843/1df7f879-c282-459f-9f17-0f2022a90881">
<img width="960" alt="image" src="https://github.com/morijyobi/python_flask_web_final_exercise_2023-itouayumu/assets/113155843/be528aa1-3f13-47f2-88c9-a9fe08a69cc2">
メール送信機能作成完了

追加要件
- パスワード変更update文実装

**Comment by itouayumu** [comment]
<img width="960" alt="image" src="https://github.com/morijyobi/python_flask_web_final_exercise_2023-itouayumu/assets/113155843/f7ca7cf1-055c-4f01-80df-2bbcd35fdf69">
作成完了
